/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BorrowersIndexRouteImport } from './routes/borrowers.index'
import { Route as BorrowersBorrowerIdRouteImport } from './routes/borrowers.$borrowerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowersIndexRoute = BorrowersIndexRouteImport.update({
  id: '/borrowers/',
  path: '/borrowers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowersBorrowerIdRoute = BorrowersBorrowerIdRouteImport.update({
  id: '/borrowers/$borrowerId',
  path: '/borrowers/$borrowerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/borrowers/$borrowerId': typeof BorrowersBorrowerIdRoute
  '/borrowers/': typeof BorrowersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/borrowers/$borrowerId': typeof BorrowersBorrowerIdRoute
  '/borrowers': typeof BorrowersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/borrowers/$borrowerId': typeof BorrowersBorrowerIdRoute
  '/borrowers/': typeof BorrowersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/borrowers/$borrowerId' | '/borrowers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/borrowers/$borrowerId' | '/borrowers'
  id: '__root__' | '/' | '/borrowers/$borrowerId' | '/borrowers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BorrowersBorrowerIdRoute: typeof BorrowersBorrowerIdRoute
  BorrowersIndexRoute: typeof BorrowersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrowers/': {
      id: '/borrowers/'
      path: '/borrowers'
      fullPath: '/borrowers/'
      preLoaderRoute: typeof BorrowersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrowers/$borrowerId': {
      id: '/borrowers/$borrowerId'
      path: '/borrowers/$borrowerId'
      fullPath: '/borrowers/$borrowerId'
      preLoaderRoute: typeof BorrowersBorrowerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BorrowersBorrowerIdRoute: BorrowersBorrowerIdRoute,
  BorrowersIndexRoute: BorrowersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
